"""private messages

Revision ID: 02e2656930fe
Revises: 61304e02cdc0
Create Date: 2021-03-31 11:36:50.931793

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02e2656930fe'
down_revision = '61304e02cdc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recommended_appliance', 'photo_id')
    op.drop_column('recommended_appliance', 'usage_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recommended_appliance', sa.Column('usage_time', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('recommended_appliance', sa.Column('photo_id', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
