"""initial Migration

Revision ID: e3f874441ba4
Revises: 6b9d5b0a5b06
Create Date: 2021-04-07 01:24:11.925792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3f874441ba4'
down_revision = '6b9d5b0a5b06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('survey', sa.Column('cookFrequency', sa.String(length=200), nullable=True))
    op.add_column('survey', sa.Column('dishWasher', sa.String(length=200), nullable=True))
    op.add_column('survey', sa.Column('hotWaterUsage', sa.String(length=200), nullable=True))
    op.add_column('survey', sa.Column('houseStories', sa.String(length=200), nullable=True))
    op.add_column('survey', sa.Column('laundryUsage', sa.String(length=200), nullable=True))
    op.add_column('survey', sa.Column('microwaveFrequency', sa.String(length=200), nullable=True))
    op.add_column('survey', sa.Column('numOfPeople', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('survey', 'numOfPeople')
    op.drop_column('survey', 'microwaveFrequency')
    op.drop_column('survey', 'laundryUsage')
    op.drop_column('survey', 'houseStories')
    op.drop_column('survey', 'hotWaterUsage')
    op.drop_column('survey', 'dishWasher')
    op.drop_column('survey', 'cookFrequency')
    # ### end Alembic commands ###
